FROM node:20

RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

RUN npm install -g npm@10.8.2

USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]