services:
  ros:
    build:
      context: .
      dockerfile: ros_ws/Containerfile
    container_name: shopassist_ros

    network_mode: host
    security_opt:
      - label=disable
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - MONGO_URI=mongodb://127.0.0.1:27017
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: shopassist_frontend
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.containers.internal:host-gateway"
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: shopassist_mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db:Z
      - ./mongo-seed:/mongo-seed:Z
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:Z
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
